[package]
name = "imdisable-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotkey = { git = "https://github.com/shiomiyan/hotkey-rs", package = "hotkey" }

[dependencies.windows]
version = "0.34.0"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_Ime",
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse"
]